import { withPayload } from '@payloadcms/next/withPayload'

/**
 * A stamp that changes with every deploy, which is what stops a browser holding
 * a stale copy of a page from rendering nothing.
 *
 * Without it, a tab opened before a deploy asks for JavaScript files that the
 * new deploy no longer has. The request 404s and the page renders blank — no
 * error, no message. It hits the admin hardest, because the admin *is*
 * JavaScript: the server answers 200 and the screen stays white, which sends
 * you looking for a server fault that is not there.
 *
 * With it, Next stamps asset URLs and navigation responses, notices the
 * mismatch, and does a full page reload instead of failing. Vercel exposes the
 * deployment id; the commit SHA is the fallback, since it also changes every
 * deploy. Undefined locally, where there is nothing to skew.
 */
const deploymentId = process.env.VERCEL_DEPLOYMENT_ID || process.env.VERCEL_GIT_COMMIT_SHA

/** @type {import('next').NextConfig} */
const nextConfig = {
  ...(deploymentId ? { deploymentId } : {}),

  /**
   * Where images may be optimised from.
   *
   * Uploads live in Vercel Blob in production, on a hostname the optimiser has
   * to be told about explicitly — an unlisted host does not fall back to the
   * original, it 400s, so a missing pattern means broken images rather than
   * merely unoptimised ones. This app's own uploads need no entry: Payload
   * stores them as absolute URLs, and `src/blocks/BlockImage.tsx` reduces those
   * back to `/api/media/file/...` so they stay same-origin on any hostname —
   * localhost, a preview deployment, or either production domain.
   */
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: '**.cloudflarestream.com' },
      { protocol: 'https', hostname: '**.public.blob.vercel-storage.com' },
      { protocol: 'https', hostname: 'ecommharvest.com' },
      { protocol: 'https', hostname: 'app.ecommharvest.com' },
    ],
  },

  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          // The lesson player embeds Cloudflare Stream in an iframe, so this
          // cannot be DENY — but nothing here may be framed by a third party.
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
        ],
      },
      {
        // Member and admin pages must never be cached by a shared proxy.
        source: '/:path(learn|members|builder|admin)/:rest*',
        headers: [{ key: 'Cache-Control', value: 'private, no-store' }],
      },
      {
        /**
         * The admin and the page builder must never be framed at all.
         * Clickjacking an authenticated admin session is the attack this
         * closes, and unlike /learn there is no Cloudflare embed to allow for,
         * so this can be DENY rather than SAMEORIGIN. `frame-ancestors` is the
         * modern equivalent and covers browsers that ignore X-Frame-Options.
         */
        source: '/:path(admin|builder)/:rest*',
        headers: [
          { key: 'X-Frame-Options', value: 'DENY' },
          { key: 'Content-Security-Policy', value: "frame-ancestors 'none'" },
        ],
      },
      /**
       * The calendar file sets its own headers now — it is generated by
       * `src/app/masterclass.ics/route.ts` rather than served from `public/`,
       * so the date can only come from `src/lib/event.ts`. Left here it would be
       * a second place claiming to decide the same two headers.
       */
    ]
  },

  async redirects() {
    /**
     * Three hostnames, two platforms:
     *
     *   ecommharvest.com      the public site — this app, published builder pages
     *   app.ecommharvest.com  admin, page builder, member area — this app
     *   go.ecommharvest.com   funnels, forms, email and SMS — GoHighLevel
     *
     * Both Vercel hostnames point at the same deployment, so every route is
     * technically reachable on both. These redirects make each host mean one
     * thing, which keeps links shareable and stops `ecommharvest.com/admin`
     * existing as a second address for the same screen.
     *
     * They are tidiness, not security. The security boundary is authentication,
     * which does not care which hostname you arrived on.
     */
    /**
     * Bare hostnames only — no port, no scheme. Next strips the port from the
     * Host header before matching (`prepare-destination.js`), so `localhost:3005`
     * silently matches nothing. The value is also treated as a regex anchored
     * with ^…$, which is why a literal hostname works but a URL does not.
     */
    const SITE_HOST = process.env.SITE_HOST || 'ecommharvest.com'
    const APP_HOST = process.env.APP_HOST || 'app.ecommharvest.com'
    const onSite = [{ type: 'host', value: SITE_HOST }]

    /** Private areas belong on app. — sent there rather than served twice. */
    const privateAreas = ['admin', 'builder', 'learn', 'members'].map((area) => ({
      source: `/${area}/:path*`,
      has: onSite,
      destination: `https://${APP_HOST}/${area}/:path*`,
      permanent: false,
    }))
    // `:path*` does not match the bare path, so each area needs its own root rule.
    const privateRoots = ['admin', 'builder', 'learn', 'members'].map((area) => ({
      source: `/${area}`,
      has: onSite,
      destination: `https://${APP_HOST}/${area}`,
      permanent: false,
    }))

    return [
      // The static build served these as .html; keep those URLs working.
      { source: '/index.html', destination: '/masterclass', permanent: true },
      { source: '/privacy.html', destination: '/privacy', permanent: true },
      { source: '/terms.html', destination: '/terms', permanent: true },
      { source: '/thanks.html', destination: '/masterclass/thanks', permanent: true },
      { source: '/thanks', destination: '/masterclass/thanks', permanent: true },
      ...privateRoots,
      ...privateAreas,
    ]
  },
}

export default withPayload(nextConfig, { devBundleServerPackages: false })
